### ISSUE TITLE
하이라이터단어 hover -> 베스트댓글이 뜬다

### ISSUE THREAD

**Issue by cannalee90** [hanseuly/bubblegum#1]

**Comment by hanseuly** [comment]
하트(좋아요) 수를 가장 많이 받은 태그가 뜬다. - 같은 부분에 여러태그가 달렸을경우..

**Comment by cannalee90** [comment]
몇가지 질문이 있습니다.
1. `이세돌`이라는 단어를 하이라이팅 하면 그 기사에 있는 모든 `이세돌`이 하이라이팅 되는지
2. 단어 하이리팅을 겹치게. `이세`, `세돌`이 가능한지

**Comment by hanseuly** [comment]
1. 지금은 그렇게 돼있는데 원래는 딱 드래그 한 그 _이세돌_만 하이라이팅 되게 하려햇던거에요ㅠㅠ! 그럴려고 기사 원문을 여러문장으로 쪼갰던걸로 기억하는데...! 도 지금 모든 _이세돌_이 하이라이팅이 돼버리네요
2. 가능하면 그렇게 했으면 좋겠어요! 그렇게 했을때 span 스타일은 제가 생각해볼게요!

**Comment by cannalee90** [comment]
일단 겹치는 단어는 없게 한다.
