### ISSUE TITLE
드래그 이벤트 가능영역 제한두기

### ISSUE THREAD

**Issue by hanseuly** [hanseuly/bubblegum#11]
main.html  에서 기사원문을 드래그했을때 1)버튼패널이 뜨는 이벤트 2)모달창에 드래그내용을 기억해서 띄우는 이벤트 가 기사원문 영역의 div (class="article_text) 에만 한정되도록

관련 코드
main.html.erb 
assets/javascripts/application.js

**Comment by cannalee90** [comment]
https://github.com/hanseuly/bubblegum/commit/9b08b5d9c1415a7e2b6f09f7fed3bad8a54718c7
