### ISSUE TITLE
listpre.html 에서 main.html로 넘어갈때

### ISSUE THREAD

**Issue by hanseuly** [hanseuly/bubblegum#14]
넘어갈수 있는 방법이 총 3가지입니다.
1. 기사제목누른다
2. 각 태그리스트의 #태그 를 누른다. -> 해당 태그가 위치하는 스크롤위치로 잡히면서 이동.
3. 각 이미지의 모달창을 띄운후 모달창 위에 적혀있는 #태그내용 을 누른다. -> 해당 태그가 위치하는 스크롤 위치로 잡히면서 이동.

즉, #태그 를 누르면서 main으로 이동했을때는 그 해당 태그가 위치하는 줄(스크롤)로 이동해야해요!

**Comment by cannalee90** [comment]
https://github.com/hanseuly/bubblegum/commit/6656df438cad85f7615c1fe1640101da120391cb
