### ISSUE TITLE
listpre.html 에서 이미지모달창에서 #태그 내용 적힐때

### ISSUE THREAD

**Issue by hanseuly** [hanseuly/bubblegum#15]
혹시 기사원문의 `#태그` 앞뒤 내용을 조금씩 들고올수잇나요..?

예를들어 `'일론 머스크'` 에 이미지를 태그해서
listpre.html에서 `#일론 머스크` 로 뜨고 - 이미지리스트가 있는데
그 중 하나의 이미지를 클릭하면 모달창이 뜨잖아요!
그때 이미지 위에 `#태그` 내용이 나오는데

최고경영자(CEO) `일론 머스크`(사진)는 ‘화성 식민지 개척’을...

로 뜨게 할수있는지!

**Comment by cannalee90** [comment]
가능합니다. 마크업 수정하면 알려주세요
