### ISSUE TITLE
하이라이터단어 click 

### ISSUE THREAD

**Issue by cannalee90** [hanseuly/bubblegum#2]
댓글목록이 뜬다 (동시에 원래 기사의 사진은 지워짐)

**Comment by cannalee90** [comment]
http://54.206.28.130/home/main/1

에서 `이세돌`을 여러번 클릭할 경우 동작되는 방식이 뭔가 랜덤같은데.. 이거 어떤식으로 동작되는건가요?

**Comment by hanseuly** [comment]
원래는
1. 하나이상 컨텐츠가 태그된 부분은 하이라이팅 된다. (ex : _이세돌_ )
2. 하이라이팅된 단어나 문장 위에 hover를 하면 -> 여러개의 컨텐츠가 태그됐다고 가정했을때: 가장 좋아요 수를 많이 받은 베스트 태그 하나만 뜬다. (미리보기개념)
3. 하이라이팅된 단어나 문장을 click 하면 -> 여러개의 컨텐츠가 태그됐다고 가정했을때: 여러개의 컨텐츠가 모두 뜬다. (리스트 순서는 좋아요순서 순으로)
4. 리스트가 로드돼있는 상태에서 리스트영역 외에 다른 부분을 클릭하게 되면 태그리스트가 사라진다. 
   -------------- Genius.com 라는 사이트가.. 이렇게 드래그->태그 할수있는 사이트인데 여기서 동작되는 방식이랑 거의 동일하시다고보면돼요 ! 여기는 패널같은게 슬라이드토글오픈/클로징 느낌인데 저는 그냥 뿅하고 나타났다가 뿅하고 사라지게끔하려했어요!

**Comment by cannalee90** [comment]
span을 click하면 list고정
다른 하이라이트를 hover해도 나오지 않는다.

**Comment by cannalee90** [comment]
https://github.com/hanseuly/bubblegum/issues/4

**Comment by cannalee90** [comment]
https://github.com/hanseuly/bubblegum/issues/3

**Comment by hanseuly** [comment]
[click-hover.pdf](https://github.com/hanseuly/bubblegum/files/560615/click-hover.pdf)

지금 1~3번까지는 잘 되는것같고 4번부터가 달라져야해요!
즉, 3번상태('일론머스크' 클릭->댓글리스트)에서 다른단어에 hover한다해도 '일론머스크'의 댓글리스트가 사라지지않아야해요!

3번상태에서 '일론머스크' 댓글리스트가 사라지게되는 조건은
1) 댓글리스트 div  영역밖을 클릭한다. (그러면 리스트가 사라지면서 기사이미지가 뜬다)
2) 다른 하이라이팅 단어를 click한다. (그러면 '일론머스크' 댓글리스트가 사라지면서 click한 해당단어의 리스트가 뜬다. - 즉 베스트댓글만 보이는 hover액션을 생략하고 바로 리스트로드가 되는거에용!)
