### ISSUE TITLE
댓글 안지워진다는 버그

### ISSUE THREAD

**Issue by cannalee90** [hanseuly/bubblegum#4]
http://54.206.28.130/home/main/1

참고

**Comment by hanseuly** [comment]
클릭이나 hover로 태그를 로드한후, 다른 영역으로 벗어나거나 다른영역을 클릭하면 로드됐던 태그들이 다시 안보여야되는데 안사라지는 버그가 있었슴니당

**Comment by cannalee90** [comment]
삭제 페이지를 못찾았는데 어떤식으로 트리거 되나요 @_@?

**Comment by hanseuly** [comment]
아아아 댓글 안지워지는버그 이거랑 이슈 #3 이랑 겹치는 내용같아요..!
삭제페이지..!?는 뭘 뜻하시는걸까요 ㅠ_ㅠ!?

**Comment by cannalee90** [comment]
아 삭제가 어떤 동작을 해야 작동을 하는지 몰라서 @_@..
