### ISSUE TITLE
각각의 태그의 이벤트

### ISSUE THREAD

**Issue by cannalee90** [hanseuly/bubblegum#6]
http://54.206.28.130/home/listpre/4 
기사 페이지의 전페이지에는 태그컨텐츠들 중 이미지컨텐츠가 로딩된다. (지금은 둥둥떠다니는데 이거 없앨것같아여 ㅋㅋㅋㅋㅋㅋ  html/css 니까 제가 하겠슴다) 
각 이미지 hover시에 해당 기사 일부분이 떠야한다 (지금은 사용자가 이미지 올리면서 썼던내용이 뜨고있슴니당ㅠㅠ)

**Comment by hanseuly** [comment]
![2016-10-26 5 23 54](https://cloud.githubusercontent.com/assets/13049299/19718607/030be79e-9ba1-11e6-8c22-6d6dcc009be1.png)
![2016-10-26 5 20 42](https://cloud.githubusercontent.com/assets/13049299/19718644/1df8bb04-9ba1-11e6-9c14-a3cd45a41e87.png)

listpre.html 관련 내용이에요
디자인은 아직 안나와서.. 그냥 간단한 스케치...이구요 (....)
일단 기능 위주로 얘기하자면,
1. listpre.html 에 뜨는 컨텐츠들은  main.html에서 사람들이 각 기사일부분을 드래그하여 태그했던 '이미지'들이다.
2. listpre.html 에는 이미지들과, 그 이미지가 어떤 단어 혹은 문장에 태그됐는지 그 단어/문장도 함께 표기된다
(이미지에서는 머스크 라고 가정해놨어요)
3. 이미지(동그라미)를 누르면 모달창으로 기사원문/이미지/유저네임/유저가 쓴 텍스트 가 뜨고, 모달창의 '기사원문'부분을 누르면 main.html 로 넘어가는데, 해당 부분이 있는 위치로 스크롤돼서 넘어간다.
4. listpre.html에서 어떤 단어 혹은 문장에 태그됐는지 표기된 단어/문장을 누르면 main.html 로 넘어가는데, 해당 부분이 있는 위치로 스크롤돼서 넘어간다.

**Comment by hanseuly** [comment]
1. listpre.html에서 어떤 단어 혹은 문장에 태그됐는지 표기된 단어/문장을 누르면 main.html 로 넘어가는데, 해당 부분이 있는 위치로 스크롤돼서 넘어간다.
