### ISSUE TITLE
list.html 에 추가로 로드해야하는 정보들

### ISSUE THREAD

**Issue by hanseuly** [hanseuly/bubblegum#8]
![2016-10-27 12 54 45](https://cloud.githubusercontent.com/assets/13049299/19733794/13d3dea8-9be0-11e6-9afc-7e35eba6578c.png)

역시나 이미지는... 그냥 급하게 스케치한것으로... 디자인은 제가 바꿀것이니 무시해주시고.. (...ㅠㅠ)
1. 각 기사에 달린 이미지댓글 개수를 보여줘야할것같아요!
   지금 보시면 두번째에 커진게 hover한 상태인건데, hover했을때 저렇게 'image댓글의 수', 'link댓글의 수'... 식으로 댓글의 종류따라 몇개씩 달렸는지 뜨게 하려구는거구요
2. 각 기사에 태그컨텐츠가 많이 달린 원문 단어(혹은 문장)이 top 3 순으로 3개정도 띄어주려고해요!
   예를들어 기사 원문중에 '테슬라 최고경영자(CEO) 일론 머스크(사진)는 '화성 식민지 개척'을 ...' 이런 문장이 있을때 사람이 '일론 머스크'를 드래그해서 태그를 막 했다치고, 그게 제일 많았다치면 '일론 머스크'가 list.html에서 뜨도록 하거든요! 가능할까욘'ㅅ'???

**Comment by hanseuly** [comment]
강호님, 
1. 에서 기사제목(빨간원) 주변에 떠다니는 (분홍색원) 정보 = 댓글개수 인데요, 종류별로(4가지) 필요하진않고 이미지댓글 개수만 불러오면 될것같아요!!!

**Comment by cannalee90** [comment]
현재 이미지 댓글은 잘 불러옵니다.

**Comment by cannalee90** [comment]
지금 로딩되는 순서는 `posts.id` 내림차순 그리고 각각의 `replies`는 `like_count`순으로 정렬되어 있습니다.

**Comment by cannalee90** [comment]
마크업만 적용되면 완료!

**Comment by hanseuly** [comment]
<%= post.image_reply_length %>
이미지 댓글개수

**Comment by cannalee90** [comment]
수정되었습니다.

**Comment by hanseuly** [comment]
각 기사에 hover하면 주변에 빙글빙글 도는 이미지댓글개수 버블이랑, 댓글이 많이달린 태그목록이 떠야하는데
한 기사에 hover했을때 4개 기사 모두 뜹니다 ㅠㅠ 살려주세여

**Comment by cannalee90** [comment]
https://github.com/hanseuly/bubblegum/commit/30995f6e3c0cc3b05ee6b1b1f786f270dc96fbc9
